### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tokk-nv**
Add descritpion for car options.

### CODE REVIEW

**Comment by jaybdub** [comment]
Thanks Chitoku.  However, having the descriptive information inline the setup instructions feels a bit out of place to me.

What do you think of instead making a small section labeled "Cars", that has a picture of each with short description / bullet points of any facts that might be relevant to user?

For example, something like this before Setup

## Cars

### Latrax Rally

Image

* 1/18th scale
* No extra transmitter required
* etc ...

### Tamiya TT02

Image

* 1/10th scale
* Requires additional 3 channel transmitter
* etc..

**Comment by tokk-nv** [comment]
Having a little section "Cars" is a good idea.

I'm good with your proposed bullet point style, which is consistent with other sections.
Do you want to explore a table format idea, basically in interest of keeping the section small?

**Comment by jaybdub** [comment]
I think bullets make more sense here, since it's more flexible to adding miscellaneous / car specific information.  Also there are only 2 entries.

But if you have an idea, you could stage in markdown in these PR comments to show what it'd look like.

**Comment by tokk-nv** [comment]
Modified the README.md to have the Cars section as suggested.

**Comment by tokk-nv** [comment]
> But if you have an idea, you could stage in markdown in these PR comments to show what it'd look like.

| **Latrax Rally** | **Tamiya TT02** | 
|:-:|:-:|
|   |   | 
| 1/18th scale | 1/10th scale | 
| Ready-To-Run. Comes fully assembled | Kit. Requires assembly | 
| Includes transmitter, batteries and the charger | Need to separately get a servo, transmitter, batteries, and charger | 
| Requires a mod to the stock transmitter for enabling CH3 | (No need of transmitter mod) |
| Moderate speed | Faster |

**Comment by jaybdub** [comment]
## Cars

|  Latrax Rally | Tamiya TT02 |
|--------------|---------------|
|   |   | 
| 1/18th scale |  1/10th scale |
| Moderate Speed  |  High Speed  |
| ~$400 total build cost | ~$600 total build cost |
| Compact and portable |  Large and easy to modify |
| Soldering required |  No soldering required  |
| Base car pre-assembled | Base car assembly required |

**Comment by tokk-nv** [comment]
Updated the Cars section with the table and new photos per our phone discussion.

**Pull request merged**
